use_frameworks!

target 'BLPhotoAssetPickerController_Example' do
  pod 'BLPhotoAssetPickerController', :path => '../'
  pod 'RMUniversalAlert'

  target 'BLPhotoAssetPickerController_Tests' do
    inherit! :search_paths


  end
end
